[project]
name = "zapret-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "aioquic>=1.2.0",
    "certifi>=2025.8.3",
    "click>=8.2.1",
    "dnspython>=2.7.0",
    "psutil>=7.0.0",
]
